//
//  INSCameraServiceHeader.h
//  INSCameraSDK
//
//  Created by insta360_ltp on 2024/8/23.
//  Copyright © 2024 insta360. All rights reserved.
//

#ifndef INSCameraServiceHeader_h
#define INSCameraServiceHeader_h

#import <INSCameraServiceSDK/INSCameraPhotographyBasic.h>
#import <INSCameraServiceSDK/INSCameraError.h>
#import <INSCameraServiceSDK/INSCameraFileMndInfo.h>
#import <INSCameraServiceSDK/INSCameraPhotoInfo.h>
#import <INSCameraServiceSDK/INSCameraVideoInfo.h>
#import <INSCameraServiceSDK/INSCameraInfo.h>
#import <INSCameraServiceSDK/INSCameraCaptureStatus.h>
#import <INSCameraServiceSDK/INSCaptureOptions.h>
#import <INSCameraServiceSDK/INSCloudOptions.h>
#import <INSCameraServiceSDK/INSUSBDevice.h>
#import <INSCameraServiceSDK/INSCameraDevice.h>
#import <INSCameraServiceSDK/INSSocketDevice.h>
#import <INSCameraServiceSDK/INSWebServerDevice.h>
#import <INSCameraServiceSDK/INSCameraManager.h>
#import <INSCameraServiceSDK/INSCameraManager+External.h>
#import <INSCameraServiceSDK/INSCameraManager+Bluetooth.h>
#import <INSCameraServiceSDK/INSCameraManager+Utils.h>
#import <INSCameraServiceSDK/INSAppKeepAlive.h>
#import <INSCameraServiceSDK/INSCameraBasicCommands.h>
#import <INSCameraServiceSDK/INSCameraHTTPCommands.h>
#import <INSCameraServiceSDK/INSCameraUSBCommands.h>
#import <INSCameraServiceSDK/NSNotification+INSCamera.h>
#import <INSCameraServiceSDK/INSTakePictureOptions.h>
#import <INSCameraServiceSDK/INSBluetoothManager.h>
#import <INSCameraServiceSDK/INSBluetoothManager+Utils.h>
#import <INSCameraServiceSDK/INSBluetoothDevice.h>
#import <INSCameraServiceSDK/INSCPUMonitor.h>
#import <INSCameraServiceSDK/INSCameraSDKLogger.h>
#import <INSCameraServiceSDK/INSButtonPressOptions.h>
#import <INSCameraServiceSDK/INSCameraGpsInfo.h>
#import <INSCameraServiceSDK/INSCameraGpsInfo+ExtraInfo.h>
#import <INSCameraServiceSDK/INSCameraTemperatureStatus.h>
#import <INSCameraServiceSDK/INSFileTrackState.h>
#import <INSCameraServiceSDK/INSPhoneAuthorizationStatus.h>
#import <INSCameraServiceSDK/INSFMGParserTool.h>
#import <INSCameraServiceSDK/INSReaderOptions.h>
#import <INSCameraServiceSDK/INSOpenWifiCaptivePortalTool.h>
#import <INSCameraServiceSDK/INSCameraServiceSDKDefine.h>
#import <INSCameraServiceSDK/INSEditInfo.h>
#import <INSCameraServiceSDK/INSEditExportInfo.h>
#import <INSCameraServiceSDK/INSEditFilterInfo.h>
#import <INSCameraServiceSDK/INSEditClipInfo.h>
#import <INSCameraServiceSDK/INSEditDashboardInfo.h>
#import <INSCameraServiceSDK/INSEditMeisheInfo.h>
#import <INSCameraServiceSDK/INSEditMultiViewInfo.h>
#import <INSCameraServiceSDK/INSProjectInfo.h>
#import <INSCameraServiceSDK/INSEditSourceInfo.h>
#import <INSCameraServiceSDK/INSLiveStreamOptions.h>
#import <INSCameraServiceSDK/INSIntervalRecInfo.h>
#import <INSCameraServiceSDK/INSCameraTimelapseStatus.h>
#import <INSCameraServiceSDK/INSCameraWifiInfo.h>
#import <INSCameraServiceSDK/INSCameraWifiChannelList.h>
#import <INSCameraServiceSDK/INSOpenIperfOption.h>
#import <INSCameraServiceSDK/INSCameraSensor.h>
#import <INSCameraServiceSDK/INSCameraBatteryStatus.h>
#import <INSCameraServiceSDK/INSChargeBoxStatus.h>
#import <INSCameraServiceSDK/INSPhotographyOptions.h>
#import <INSCameraServiceSDK/INSCameraStorageStatus.h>
#import <INSCameraServiceSDK/INSGyroFilterOptions.h>
#import <INSCameraServiceSDK/INSUpgradeStateOptions.h>
#import <INSCameraServiceSDK/INSWindowCropInfo.h>
#import <INSCameraServiceSDK/INSLiveStreamParamsUpdate.h>
#import <INSCameraServiceSDK/INSDetectFace.h>
#import <INSCameraServiceSDK/INSNoticDarkEisStatus.h>
#import <INSCameraServiceSDK/INSNotificationCloudUploadStatus.h>
#import <INSCameraServiceSDK/INSUsbCardStatus.h>
#import <INSCameraServiceSDK/INSCameraOptions.h>
#import <INSCameraServiceSDK/INSCameraWriteFileOptions.h>
#import <INSCameraServiceSDK/INSTimelapseOptions.h>
#import <INSCameraServiceSDK/INSCameraBTPeripheral.h>
#import <INSCameraServiceSDK/INSCameraCalibrateGyroOptions.h>
#import <INSCameraServiceSDK/INSGetFileListOptions.h>
#import <INSCameraServiceSDK/INSGetGyroOptions.h>
#import <INSCameraServiceSDK/INSTestSDCardOptions.h>
#import <INSCameraServiceSDK/INSSyncMediaTimeResult.h>
#import <INSCameraServiceSDK/INSHeartbeatsSenderOptions.h>
#import <INSCameraServiceSDK/INSKeyTimePoint.h>
#import <INSCameraServiceSDK/INSGetFileResp.h>
#import <INSCameraServiceSDK/INSCloudStorageUploadParams.h>
#import <INSCameraServiceSDK/INSLiveCtrlInfo.h>
#import <INSCameraServiceSDK/INSWifiScanInfo.h>
#import <INSCameraServiceSDK/INSCloudStorageInfo.h>
#import <INSCameraServiceSDK/INSDownLoadInfo.h>
#import <INSCameraServiceSDK/INSNotifyCameraSubMode.h>
#import <INSCameraServiceSDK/INSNotificationDeleteFileOperation.h>
#import <INSCameraServiceSDK/INSCameraSimpleCommands.h>
#import <INSCameraServiceSDK/INSCtrlPreRecord.h>
#import <INSCameraServiceSDK/INSDashCamInfo.h>
#import <INSCameraServiceSDK/INSBulletTimeOptions.h>
#import <INSCameraServiceSDK/INSHDRVideoOptions.h>
#import <INSCameraServiceSDK/INSProxyFileInfo.h>
#import <INSCameraServiceSDK/INSPanoFPVInfo.h>
#endif /* INSCameraServiceHeader_h */
